export interface CommessaIniziale {
  codiceCommessa: string;
  anno: string;
  tipologia: string;
  titolo: string;
  cliente: string;
  stato: string;
  responsabile: string;
  pm: string;
}

export const TIPOLOGIA_COLORS: Record<string, string> = {
  'A': '#ef4444',   // Rosso
  'AE': '#38bdf8',  // Azzurro
  'B': '#3b82f6',   // Blu
  'CA': '#10b981',  // Smeraldo
  'CE': '#f59e0b',  // Ambra
  'CF': '#8b5cf6',  // Viola
  'CO': '#ec4899',  // Rosa
  'CS': '#06b6d4',  // Ciano
  'DL': '#14b8a6',  // Teal
  'E': '#f97316',   // Arancione
  'F': '#a855f7',   // Porpora
  'G': '#111827',   // Nero
  'M': '#d97706',   // Ambra Scuro
  'P': '#6366f1',   // Indaco
  'PE': '#a855f7',  // Porpora
  'PR': '#eab308',  // Giallo
  'R': '#84cc16',   // Lime
  'RF': '#22c55e',  // Verde
  'RI': '#0ea5e9',  // Sky
  'S': '#d946ef',   // Magenta
  'SF': '#f43f5e',  // Rosa scuro
  'U': '#475569',   // Ardesia scuro
  'V': '#64748b',   // Ardesia
};

export const COMMESSE_INIZIALI: CommessaIniziale[] = [
  { codiceCommessa: "A210219A", anno: "2021", tipologia: "A", titolo: "PRATICHE ANTINCENDIO E INAIL CENTRALI BIOMASSA GARFAGNANA", cliente: "R&S S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Beatrice Barni" },
  { codiceCommessa: "A260061B", anno: "2026", tipologia: "A", titolo: "PRATICA RINNOVO CONCESSIONE POZZO SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Francesca Turi" },
  { codiceCommessa: "A260132A", anno: "2026", tipologia: "A", titolo: "PRATICHE CODICI ATECO AZIENDE GRUPPO", cliente: "A. MENARINI MANUFACTURING LOGISTICS AND SERVICES S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "B210055A", anno: "2021", tipologia: "B", titolo: "PROGETTAZIONE ESECUTIVA EX DISCARICA BACCACIANO", cliente: "COMUNE DI SARTEANO", stato: "Aperta", responsabile: "Andrea Profeti", pm: "" },
  { codiceCommessa: "B230260A", anno: "2023", tipologia: "B", titolo: "PROGETTAZIONE BONIFICA E MISP REZZAIA PIETRASANTA", cliente: "COMUNE DI PIETRASANTA", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Francesca Turi" },
  { codiceCommessa: "B260291A", anno: "2026", tipologia: "B", titolo: "PROG BONIFICA TERRENI INSATURI PRIOLO GARGALLO", cliente: "STANTEC S.P.A.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Francesca Turi" },
  { codiceCommessa: "B260308A", anno: "2026", tipologia: "B", titolo: "BONIFICA SITO LI-1019 ROSIGNANO SOLVAY", cliente: "UNICOOP ETRURIA S.C.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Francesca Turi" },
  { codiceCommessa: "B260313A", anno: "2026", tipologia: "B", titolo: "PROG SPOSTAMENTO POZZO CD2 P&T MONTESCUDAIO", cliente: "COMIS SRL", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Francesca Turi" },
  { codiceCommessa: "CA240206B", anno: "2024", tipologia: "CA", titolo: "CONSULENZA AMBIENTE SICUREZZA ANEMOCYTE TURATE", cliente: "TECHNICONSULT FIRENZE S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "" },
  { codiceCommessa: "CA240285A", anno: "2024", tipologia: "CA", titolo: "CONSULENZA AMBIENTALE", cliente: "GLYCO S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Francesca Turi" },
  { codiceCommessa: "CA260132A", anno: "2026", tipologia: "CA", titolo: "CONSULENZA AMBIENTALE DEPURATORI AREA FIORENTINA 2026", cliente: "A. MENARINI MANUFACTURING LOGISTICS AND SERVICES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "" },
  { codiceCommessa: "CF260304A", anno: "2026", tipologia: "CF", titolo: "CORSO RLS E-LEARNING", cliente: "ACA S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CO200154A", anno: "2020", tipologia: "CO", titolo: "CONSULENZA DI STABILIMENTO", cliente: "EDRA S.P.A.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "" },
  { codiceCommessa: "CO220117A", anno: "2022", tipologia: "CO", titolo: "DIREZIONE ESECUZIONE E SUPERVISIONE P&T MONTESCUDAIO", cliente: "REGIONE TOSCANA", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Francesca Turi" },
  { codiceCommessa: "CO220243A", anno: "2022", tipologia: "CO", titolo: "CONSULENZA COGENERATORE BIOGAS GROSSETO", cliente: "ACQUEDOTTO DEL FIORA S.P.A.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "CO230270A", anno: "2023", tipologia: "CO", titolo: "ASSISTENZA AL PERMITTING", cliente: "N.S.C. HOSPITAL S.C.A.R.L.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "" },
  { codiceCommessa: "CO250185B", anno: "2025", tipologia: "CO", titolo: "ASSISTENZA E CONSULENZA INAIL-PED", cliente: "TAKEDA ITALIA S.P.A.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CO260061A", anno: "2026", tipologia: "CO", titolo: "CONSULENZA CONNESSIONE UTILITIES NEW LABS SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Niccolò Rossi" },
  { codiceCommessa: "CO260061B", anno: "2026", tipologia: "CO", titolo: "SERVIZI COLLEGAMENTO CENTRALI ANTINCENDIO", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "CO260132A", anno: "2026", tipologia: "CO", titolo: "CONSULENZA AMBIENTE/SICUREZZA IN ECONOMIA 2026", cliente: "A. MENARINI MANUFACTURING LOGISTICS AND SERVICES S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CO260185A", anno: "2026", tipologia: "CO", titolo: "CONSULENZA CONTINGENCY RELIABILITY PLAN HVAC", cliente: "TAKEDA ITALIA S.P.A.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "CO260198A", anno: "2026", tipologia: "CO", titolo: "HSE ADVISOR PROGETTO PARMA BECOMIX 125", cliente: "GSK MANUFACTURING S.P.A.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "CO260269A", anno: "2026", tipologia: "CO", titolo: "CONSULENZA LA COLLINA APP. 4A1 PER VERIFICA PERDITA", cliente: "TENUTA DI CASTELFALFI S.P.A.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "" },
  { codiceCommessa: "CO260295A", anno: "2026", tipologia: "CO", titolo: "CONSULENZA WWTP NEXT GEN SESTO FIORENTINO", cliente: "ELI LILLY ITALIA S.P.A.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "" },
  { codiceCommessa: "CO260315A", anno: "2026", tipologia: "CO", titolo: "GARA LAVORI ALLESTIMENTO CELLA 5 DISCARICA BULERA POMARANCE", cliente: "GRANCHI S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "" },
  { codiceCommessa: "CS230129A", anno: "2023", tipologia: "CS", titolo: "GESTIONE POS AZIENDALI", cliente: "BATTIGALLI S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "CS230185B", anno: "2023", tipologia: "CS", titolo: "CONSULENZA SICUREZZA PROCEDURE LO-TO", cliente: "TAKEDA ITALIA S.P.A.", stato: "Aperta", responsabile: "Votino Federica", pm: "SI" },
  { codiceCommessa: "CS240273A", anno: "2024", tipologia: "CS", titolo: "REDAZIONE SISTEMA DI GESTIONE ISO 9001", cliente: "EM 2001 SRL", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS240281A", anno: "2024", tipologia: "CS", titolo: "ASSISTENZA SGI 9001-14001", cliente: "SANTINI ROTTAMI SRL", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS250009A", anno: "2025", tipologia: "CS", titolo: "ASSISTENZA IN MATERIA DI SALUTE E SICUREZZA", cliente: "DELTACQUE S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS250143B", anno: "2025", tipologia: "CS", titolo: "INCARICO ASPP", cliente: "GHIROPELLI S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS250152A", anno: "2025", tipologia: "CS", titolo: "INCARICO RSPP", cliente: "MEDLINE INT. ITALY S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS250154B", anno: "2025", tipologia: "CS", titolo: "INCARICO RSPP", cliente: "EDRA S.P.A.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS250235B", anno: "2025", tipologia: "CS", titolo: "ASSISTENZA ANNUALE IGIENE ALIMENTARE", cliente: "NUTRICOM S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS250237A", anno: "2025", tipologia: "CS", titolo: "ASSISTENZA ANNUALE IGIENE ALIMENTARE", cliente: "GASPERINI RICCARDO S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS250304A", anno: "2025", tipologia: "CS", titolo: "INCARICO RSPP", cliente: "ACA S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260084A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "NICK WINTERS ITALIA S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260084B", anno: "2026", tipologia: "CS", titolo: "REGISTRAZIONE REG. CE 852/04", cliente: "NICK WINTERS ITALIA S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260126A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026 - 2027", cliente: "OFFICINA BARTALONI S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260145A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "TOSCANA FRIDGE S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260148A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "STUDIO ASSOCIATO GLM", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260159A", anno: "2026", tipologia: "CS", titolo: "ASSISTENZA ISO 9001:2015", cliente: "AIRONE SOCIETà COOPERATIVA", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260168B", anno: "2026", tipologia: "CS", titolo: "ASSISTENZA DOCUMENTAZIONE LOGISICUR", cliente: "M.S. FORMAZIONE S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260168C", anno: "2026", tipologia: "CS", titolo: "DOCENZA E ASSISTENZA PROGETTO KEDRION", cliente: "M.S. FORMAZIONE S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260179A", anno: "2026", tipologia: "CS", titolo: "CAMPIONAMENTO E DVR LEGIONELLA", cliente: "MAINTECH S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260188A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "STUDIO COMMERCIALE GALLI", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260200A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "VIGNETO SAN MIGUEL SOCIETà AGRICOLA R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260208A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "ITALIANA SERVIZI S.P.A.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260208B", anno: "2026", tipologia: "CS", titolo: "CONSULENZA SALUTE E SICUREZZA", cliente: "ITALIANA SERVIZI S.P.A.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260223A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "RELAIS UFFIZI S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260223B", anno: "2026", tipologia: "CS", titolo: "AGGIORNAMENTO MANUALE HACCP", cliente: "RELAIS UFFIZI S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260268A", anno: "2026", tipologia: "CS", titolo: "ASSISTENZA SALUTE, SICUREZZA ED IGIENE ALIMENTARE", cliente: "MONTORZO S.S.A.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260277A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "AGRISOLE S.S.A DI CAPUTO F. & C.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260281A", anno: "2026", tipologia: "CS", titolo: "CONSULENZA SALUTE E SICUREZZA", cliente: "SANTINI ROTTAMI SRL", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260287A", anno: "2026", tipologia: "CS", titolo: "INCARICO ASPP 2026", cliente: "SEBACH S.P.A. UNIPERSONALE", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260287B", anno: "2026", tipologia: "CS", titolo: "ASSISTENZA SISTEMI DI GESTIONE", cliente: "SEBACH S.P.A. UNIPERSONALE", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260288A", anno: "2026", tipologia: "CS", titolo: "INCARICO ASPP 2026", cliente: "ARMAL S.P.A. UNIPERSONALE", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260288B", anno: "2026", tipologia: "CS", titolo: "ASSISTENZA SISTEMI DI GESTIONE", cliente: "ARMAL S.P.A. UNIPERSONALE", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260293A", anno: "2026", tipologia: "CS", titolo: "PRATICA DI INIZIO ATTIVITà E AGGIORNAMENTO DVR", cliente: "CDC STUDIO S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260293B", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "CDC STUDIO S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260298A", anno: "2026", tipologia: "CS", titolo: "DOCENZA FORMAZIONE ASR - RISCHIO ALTO", cliente: "STUDIO PARENTINI ZEGA BERTELLI S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260307A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP", cliente: "PACINI EDITORE S.R.L.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260310A", anno: "2026", tipologia: "CS", titolo: "CONSULENZA E ASSISTENZA HACCP", cliente: "I SEMINANTI DI EMANUELE BIANUCCI", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260312A", anno: "2026", tipologia: "CS", titolo: "ASSISTENZA SALUTE, SICUREZZA ED IGIENE ALIMENTARE", cliente: "PIZZALVOLO S.N.C. DI SCARFALLOTO EMANUELE & C.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "CS260314A", anno: "2026", tipologia: "CS", titolo: "INCARICO RSPP 2026", cliente: "FERRARO LOGISTICA S.R.L.S.", stato: "Aperta", responsabile: "Votino Federica", pm: "" },
  { codiceCommessa: "DL240271A", anno: "2024", tipologia: "DL", titolo: "LAVORI RISTRUTTURAZIONE SALA NECROSCOPICA LATINA", cliente: "IZSLT - ISTITUTO ZOOPROFILATTICO SPERIMENTALE DEL LAZIO E DELLA TOSCANA M. ALEANDRI", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Alessio Puliti" },
  { codiceCommessa: "DL250061A", anno: "2025", tipologia: "DL", titolo: "SERVIZI LAVORI IMPIANTI FOTOVOLTAICI SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Marco Cappelli" },
  { codiceCommessa: "DL250061B", anno: "2025", tipologia: "DL", titolo: "DL - CM SOSTITUZIONE COMPRESSORI B41 GSK ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "Niccolò Rossi" },
  { codiceCommessa: "DL250276A", anno: "2025", tipologia: "DL", titolo: "DIREZIONE OPERATIVA REVAMPING LINEE DENOX WTE TORINO TRM", cliente: "GRUPPO INGEGNERIA TORINO S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "DL260061A", anno: "2026", tipologia: "DL", titolo: "CM B22 FIRE PROTECTION & SMOKE DETECTOR", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Davide Marchetti" },
  { codiceCommessa: "E240009B", anno: "2024", tipologia: "E", titolo: "PROGETTO NUOVO WWTP FRIKOM - SERBIA", cliente: "DELTACQUE S.R.L.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "Andrea Romanello" },
  { codiceCommessa: "E250061B", anno: "2025", tipologia: "E", titolo: "GESTIONE DOC MERIDIAN - PROGETTI SARDONE", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Andrea Romanello" },
  { codiceCommessa: "E250296A", anno: "2025", tipologia: "E", titolo: "EDITING IMPIANTO ACQUA DEMINERALIZZATA - ACEA", cliente: "FILDROP S.R.L.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "Andrea Romanello" },
  { codiceCommessa: "E250296B", anno: "2025", tipologia: "E", titolo: "EDITING IMPIANTI 3D", cliente: "FILDROP S.R.L.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "Andrea Romanello" },
  { codiceCommessa: "E260061A", anno: "2026", tipologia: "E", titolo: "GESTIONE DOC MERIDIAN GSK 2026", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Andrea Romanello" },
  { codiceCommessa: "E260061B", anno: "2026", tipologia: "E", titolo: "EDITING EMERGENCY PLAN ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Andrea Romanello" },
  { codiceCommessa: "E260061C", anno: "2026", tipologia: "E", titolo: "CENSIMENTO DISEGNI F&U SU MERIDIAN ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Andrea Romanello" },
  { codiceCommessa: "E260061D", anno: "2026", tipologia: "E", titolo: "GSK SIENA - GESTIONE DOC MERIDIAN 2026", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Andrea Romanello" },
  { codiceCommessa: "E260285A", anno: "2026", tipologia: "E", titolo: "EDITING P&ID IMPIANTI PROCESSO", cliente: "GLYCO S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Andrea Romanello" },
  { codiceCommessa: "F260000A", anno: "2026", tipologia: "F", titolo: "FORMAZIONE", cliente: "INGEGNO P & C S.R.L.", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "G260000A", anno: "2026", tipologia: "G", titolo: "GARE PER ENTI PUBBLICI", cliente: "INGEGNO P & C S.R.L.", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "G260000B", anno: "2026", tipologia: "G", titolo: "GARE PER ENTI/SOGGETTI PRIVATI", cliente: "INGEGNO P & C S.R.L.", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "M24P151A", anno: "2024", tipologia: "M", titolo: "EDITING VARI", cliente: "PROFETI ANDREA", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "P210094A", anno: "2021", tipologia: "P", titolo: "PROG RISTRUTTURAZ PIAZZA GARIBALDI", cliente: "COMUNE DI CASTELFRANCO DI SOTTO", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Niccolò Rossi" },
  { codiceCommessa: "P210218A", anno: "2021", tipologia: "P", titolo: "PROG IMPIANTI POLIZIA FIRENZE", cliente: "ING. RICCARDO DEL CORSO", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "P220224A", anno: "2022", tipologia: "P", titolo: "PROGETTAZIONE IMPIANTI CITTà GIARDINO TERRANUOVA BRACCIOLINI", cliente: "EUROSTUDIO INGEGNERIA - STUDIO TECNICO ASSOCIATO", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Marco Cappelli" },
  { codiceCommessa: "P230061C", anno: "2023", tipologia: "P", titolo: "PROGETTAZIONE IMPIANTI FOTOVOLTAICI SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Marco Cappelli" },
  { codiceCommessa: "P230061E", anno: "2023", tipologia: "P", titolo: "PROG INTERVENTI ADEGUAMENTO IMP ELETTRICI DEL. ARERA 540/21 ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "P230061G", anno: "2023", tipologia: "P", titolo: "SERVIZI INGEGNERIA ESECUZIONE PROGETTO FV ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Marco Cappelli" },
  { codiceCommessa: "P230083A", anno: "2023", tipologia: "P", titolo: "PROGETTO IMPIANTI TERMICI RIFUGI MUGELLO", cliente: "UNIONE MONTANA DEI COMUNI DEL MUGELLO", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Alessio Puliti" },
  { codiceCommessa: "P230150A", anno: "2023", tipologia: "P", titolo: "PROGETTAZIONE IMPIANTI PINQUA EX FANCIULLACCI", cliente: "COMUNE DI MONTELUPO FIORENTINO", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Alessio Puliti" },
  { codiceCommessa: "P230154A", anno: "2023", tipologia: "P", titolo: "PROGETTAZIONE AREA EX DI BRIZZI", cliente: "EDRA S.P.A.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "" },
  { codiceCommessa: "P230206H", anno: "2023", tipologia: "P", titolo: "PROGETTO SOTTOSERVIZI ESTERNI NOVARTIS - IVREA", cliente: "TECHNICONSULT FIRENZE S.R.L.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "" },
  { codiceCommessa: "P230211A", anno: "2023", tipologia: "P", titolo: "PROGETTAZIONE REVAMPING DEPURATORE", cliente: "CATALENT PHARMA SOLUTIONS", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Alessio Puliti" },
  { codiceCommessa: "P230244A", anno: "2023", tipologia: "P", titolo: "PROGETTO FV CABO - GSK PARMA", cliente: "SOF S.P.A.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "Marco Cappelli" },
  { codiceCommessa: "P240009A", anno: "2024", tipologia: "P", titolo: "PROGETTAZIONE WWTP ROBBIKI - EGITTO", cliente: "DELTACQUE S.R.L.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "Andrea Romanello" },
  { codiceCommessa: "P240061B", anno: "2024", tipologia: "P", titolo: "SERVIZI INGEGNERIA PROGETTO CRIOGENIA S35 SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "Niccolò Rossi" },
  { codiceCommessa: "P240061E", anno: "2024", tipologia: "P", titolo: "PROG LAVORI ADEGUAM DELIB ARERA 540/21 CONTROLLORE CENTRALE DI IMPIANTO CCI SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "P240061G", anno: "2024", tipologia: "P", titolo: "PROGETTO REVAMPING SISTEMA ACQUA CALDA ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Marco Cappelli" },
  { codiceCommessa: "P240154A", anno: "2024", tipologia: "P", titolo: "RISTRUTTURAZIONE EDIFICI 03-04-05", cliente: "EDRA S.P.A.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "" },
  { codiceCommessa: "P240184A", anno: "2024", tipologia: "P", titolo: "PROG DL CM RISANAMENTO FOGNATURE", cliente: "FIDIA FARMACEUTICI S.P.A.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Alessio Puliti" },
  { codiceCommessa: "P240261A", anno: "2024", tipologia: "P", titolo: "SERVIZI INGEGNERIA NUOVO MAGAZZINO S9 SIENA", cliente: "GVGH - GSK VACCINES INSTITUTE FOR GLOBAL HEALTH S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "P250061A", anno: "2025", tipologia: "P", titolo: "PROGETTAZIONE E PERMITTING NUOVA PORTINERIA ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "" },
  { codiceCommessa: "P250061B", anno: "2025", tipologia: "P", titolo: "NUOVE LINEE VAPORE E ACQUA ADDOLCITA B42", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "P250061C", anno: "2025", tipologia: "P", titolo: "SOSTITUZIONE CHILLER B41 ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "P250061D", anno: "2025", tipologia: "P", titolo: "RECUPERO ENERGIA TERMICA TRIGENERATORE SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Marco Cappelli" },
  { codiceCommessa: "P250061E", anno: "2025", tipologia: "P", titolo: "SOSTITUZIONE CALDAIE E CHILLER VILLA GORI", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Marco Cappelli" },
  { codiceCommessa: "P250061F", anno: "2025", tipologia: "P", titolo: "SERVIZI MODIFICA UFFICI B06 ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "P250061G", anno: "2025", tipologia: "P", titolo: "SERVIZI NUOVO TORNELLO B35 ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "P250061H", anno: "2025", tipologia: "P", titolo: "SERVIZI DEMOLIZIONE EDIFICIO S12B SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "Niccolò Rossi" },
  { codiceCommessa: "P250061I", anno: "2025", tipologia: "P", titolo: "PROGETTO REVAMPING INFRASTRUTTURA METERING SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "Marco Cappelli" },
  { codiceCommessa: "P250061J", anno: "2025", tipologia: "P", titolo: "PROGETTO EFFICIENTAMENTO ENERGETICO HVAC & UTILITIES SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "Marco Cappelli" },
  { codiceCommessa: "P250061K", anno: "2025", tipologia: "P", titolo: "INGEGNERIA SOSTITUZIONE COMPRESSORI B41 GSK ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "P250083A", anno: "2025", tipologia: "P", titolo: "PROGETTAZIONE NUOVA LINEA GAS CENTRO CARNI", cliente: "UNIONE MONTANA DEI COMUNI DEL MUGELLO", stato: "Aperta", responsabile: "Federico Badalassi", pm: "Alessio Puliti" },
  { codiceCommessa: "P250129B", anno: "2025", tipologia: "P", titolo: "SERVIZI RETE DISTRIBUZIONE ACQUA CALDA B53 GSK ROSIA", cliente: "BATTIGALLI S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "P250129D", anno: "2025", tipologia: "P", titolo: "PROGETTO STAFFAGGI LINEE IS-ISC-SW GSK ROSIA", cliente: "BATTIGALLI S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Andrea Romanello" },
  { codiceCommessa: "P250129E", anno: "2025", tipologia: "P", titolo: "PROGETTO STAFFAGGI LINEE CHILLER B41 GSK ROSIA", cliente: "BATTIGALLI S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Andrea Romanello" },
  { codiceCommessa: "P250132A", anno: "2025", tipologia: "P", titolo: "PROGETTO SOSTITUZIONE QUADRO ELETTRICO WWTP CRM", cliente: "A. MENARINI MANUFACTURING LOGISTICS AND SERVICES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Francesca Turi" },
  { codiceCommessa: "P250185A", anno: "2025", tipologia: "P", titolo: "PROGETTO SOSTITUZIONE GENERATORE VAPORE", cliente: "TAKEDA ITALIA S.P.A.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "Alessio Puliti" },
  { codiceCommessa: "P250198A", anno: "2025", tipologia: "P", titolo: "SERVIZI INGEGNERIA SOSTITUZIONE CHILLER", cliente: "GSK MANUFACTURING S.P.A.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Niccolò Rossi" },
  { codiceCommessa: "P250206C", anno: "2025", tipologia: "P", titolo: "PROGETTO SISTEMI RACCOLTA REFLUI NOVARTIS - IVREA", cliente: "TECHNICONSULT FIRENZE S.R.L.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "Andrea Romanello" },
  { codiceCommessa: "P250244A", anno: "2025", tipologia: "P", titolo: "PROG CABINA B35 E COLLEGAMENTI FV GSK ROSIA", cliente: "SOF S.P.A.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "P250269C", anno: "2025", tipologia: "P", titolo: "SERVIZI INGEGNERIA ADEGUAMENTO AREA PISCINE", cliente: "TENUTA DI CASTELFALFI S.P.A.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "P250303A", anno: "2025", tipologia: "P", titolo: "SERVIZI INGEGNERIA REVAMPING HW B23 ROSIA", cliente: "TECNOLCHI SRL", stato: "Aperta", responsabile: "Paolo Taddei", pm: "" },
  { codiceCommessa: "P260061A", anno: "2026", tipologia: "P", titolo: "ADVANCED BASIC DESIGN REVAMPING SOFFITTE B22", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "P260132A", anno: "2026", tipologia: "P", titolo: "AGGIORNAMENTO 2 PROGETTO WWTP SETTE SANTI", cliente: "A. MENARINI MANUFACTURING LOGISTICS AND SERVICES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "" },
  { codiceCommessa: "P260185A", anno: "2026", tipologia: "P", titolo: "SERVIZI NUOVO STOCCAGGIO CHEMICALS", cliente: "TAKEDA ITALIA S.P.A.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Andrea Romanello" },
  { codiceCommessa: "P260202A", anno: "2026", tipologia: "P", titolo: "PROG MODIFICHE INTERNE BISARCHA VIA TEGULAIA", cliente: "LABORATORI ARCHA SRL", stato: "Aperta", responsabile: "Giovanni Orsi", pm: "" },
  { codiceCommessa: "P260206A", anno: "2026", tipologia: "P", titolo: "PROG AREE ESTERNE ED 441 NOVARTIS HUNINGUE FRANCIA", cliente: "TECHNICONSULT FIRENZE S.R.L.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "Andrea Romanello" },
  { codiceCommessa: "P260220A", anno: "2026", tipologia: "P", titolo: "PROG STAFFAGGI AREA VASCHE INTERRATE PROGETTO TRD - NOVARTIS IVREA", cliente: "TECMA S.R.L. UNIPERSONALE", stato: "Aperta", responsabile: "Andrea Romanello", pm: "" },
  { codiceCommessa: "P260269A", anno: "2026", tipologia: "P", titolo: "MODIFICA IMPIANTO ELETTRICO MENSA", cliente: "TENUTA DI CASTELFALFI S.P.A.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "Giovanni Orsi" },
  { codiceCommessa: "P260293A", anno: "2026", tipologia: "P", titolo: "PROGETTO IMPIANTO ELETTRICO VIA ROSSELLI", cliente: "CDC STUDIO S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Giovanni Orsi" },
  { codiceCommessa: "P260311A", anno: "2026", tipologia: "P", titolo: "PROG-DL-CS RISTRUTTURAZIONE IMMOBILE CERTALDO", cliente: "ANDER’S S.R.L.", stato: "Aperta", responsabile: "Matteo Corbellini", pm: "" },
  { codiceCommessa: "PE250087A", anno: "2025", tipologia: "PE", titolo: "CTU  SHULI VS BLACK STONE", cliente: "TRIBUNALE DI PISA", stato: "Aperta", responsabile: "Andrea Profeti", pm: "" },
  { codiceCommessa: "PE250300A", anno: "2025", tipologia: "PE", titolo: "DICHIARAZIONE RISPONDENZA BAR ARCOBALENO", cliente: "BAR ARCOBALENO S.R.L.S.", stato: "Aperta", responsabile: "Giovanni Orsi", pm: "" },
  { codiceCommessa: "PE260087A", anno: "2026", tipologia: "PE", titolo: "CTU FOTOVOLTAICO PISA", cliente: "TRIBUNALE DI PISA", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "S240061L", anno: "2024", tipologia: "S", titolo: "CSP-CSE GLYCO REVOLUTION PROJECT PHASE 2", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S240061M", anno: "2024", tipologia: "S", titolo: "SICUREZZA EDS PROJECT KILLING SYSTEM S30 SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S240261A", anno: "2024", tipologia: "S", titolo: "CSP-CSE MAGAZZINO S9 SIENA", cliente: "GVGH - GSK VACCINES INSTITUTE FOR GLOBAL HEALTH S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S250061C", anno: "2025", tipologia: "S", titolo: "GESTIONE SICUREZZA CANTIERE INSTALLAZIONE AUTOCLAVE AU-F2692 ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S250061D", anno: "2025", tipologia: "S", titolo: "SERVIZI SICUREZZA OMV B - B40 AGS ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S250061H", anno: "2025", tipologia: "S", titolo: "SICUREZZA CANTIERI STRADE, MENSA, NEW LEARNING ZONE ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S250061J", anno: "2025", tipologia: "S", titolo: "CSE CANTIERE RB612 B22 AVI RELOCATION", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S250061K", anno: "2025", tipologia: "S", titolo: "ASSISTENZA LAVORI WINDOWS OBSOLESCENCE ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S250061L", anno: "2025", tipologia: "S", titolo: "SICUREZZA SOSTITUZIONE COMPRESSORI B41 GSK ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061A", anno: "2026", tipologia: "S", titolo: "SICUREZZA SOSTITUZIONE MACCHINARI PACKAGING B22 ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061C", anno: "2026", tipologia: "S", titolo: "GESTIONE DUVRI BAS DESIGO UPGRADE", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061D", anno: "2026", tipologia: "S", titolo: "SICUREZZA DUVRI STRISCE PAVIMENTI B17-39-50", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061E", anno: "2026", tipologia: "S", titolo: "CSP-CSE B22 FIRE PROTECTION & SMOKE DETECTOR", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061F", anno: "2026", tipologia: "S", titolo: "ASSISTENZA LAVORI MRNA PROJECT B20 ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061G", anno: "2026", tipologia: "S", titolo: "GESTIONE SICUREZZA TECH REFRESH ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061H", anno: "2026", tipologia: "S", titolo: "GESTIONE SICUREZZA NEW COMBO B42 ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061I", anno: "2026", tipologia: "S", titolo: "GESTIONE SICUREZZA WINDOWS SERVER 12 OBSOLESCENCE", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061J", anno: "2026", tipologia: "S", titolo: "SICUREZZA AMPLIAMENTO ARIA COMPRESSA B40", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061K", anno: "2026", tipologia: "S", titolo: "GESTIONE SICUREZZA CELLA WAREHOUSE ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Serena Boni", pm: "Davide Marchetti" },
  { codiceCommessa: "S260061L", anno: "2026", tipologia: "S", titolo: "ASSISTENZA LAVORI MANUTENZIONE FERMENTATORE B40", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Davide Marchetti", pm: "" },
  { codiceCommessa: "SF250061C", anno: "2025", tipologia: "SF", titolo: "PROGETTO ENERGY SAVING POST KAIZEN SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Andrea Profeti", pm: "Marco Cappelli" },
  { codiceCommessa: "SF250276A", anno: "2025", tipologia: "SF", titolo: "PROG FATTIBILITà MIGLIORIE TRATTAMENTO FUMI TRM PARMA", cliente: "GRUPPO INGEGNERIA TORINO S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "SF260061A", anno: "2026", tipologia: "SF", titolo: "SISTEMA SIP SCARICHI BSL2 S30 SIENA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "SF260061B", anno: "2026", tipologia: "SF", titolo: "PROGETTO FATTIBILITà INSTALLAZIONE RILEVATORI GAS ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "SF260061C", anno: "2026", tipologia: "SF", titolo: "B41 POWER CENTER REVAMPING ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Giovanni Orsi" },
  { codiceCommessa: "SF260061D", anno: "2026", tipologia: "SF", titolo: "PROGETTO FATTIBILITà SOSTITUZIONE GE B23 ROSIA", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Paolo Taddei", pm: "Giovanni Orsi" },
  { codiceCommessa: "SF260061E", anno: "2026", tipologia: "SF", titolo: "OTTIMIZZAZIONE CONSUMO ACQUA AUTOCLAVE AU-T0512", cliente: "GSK VACCINES S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "SF260211A", anno: "2026", tipologia: "SF", titolo: "PROGETTO FATTIBILITà SUDDIVISIONE PROCESSO WWTP ANAGNI", cliente: "CATALENT PHARMA SOLUTIONS", stato: "Aperta", responsabile: "Andrea Profeti", pm: "" },
  { codiceCommessa: "SF260306A", anno: "2026", tipologia: "SF", titolo: "REALIZZAZIONE NUOVO LABORATORIO GMP", cliente: "L. MOLTENI & C. DEI F.LLI ALITTI SOC. IMMOBILIARE S.R.L.", stato: "Aperta", responsabile: "Federico Badalassi", pm: "" },
  { codiceCommessa: "U18F204A", anno: "2018", tipologia: "U", titolo: "SPESE AMMINISTRATIVE-SEGRETERIA", cliente: "ERRESSE STUDIO LEGALE ASSOCIATO - AVV. GIANNA REGOLI E AVV. CRISTINA SBRANA", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "U260000A", anno: "2026", tipologia: "U", titolo: "GESTIONE UFFICIO E ATTIVITà VARIE", cliente: "INGEGNO P & C S.R.L.", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "U260000B", anno: "2026", tipologia: "U", titolo: "SISTEMA DI GESTIONE QUALITà, AMBIENTE E SICUREZZA", cliente: "INGEGNO P & C S.R.L.", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "U260000C", anno: "2026", tipologia: "U", titolo: "ATTIVITà COMMERCIALE", cliente: "INGEGNO P & C S.R.L.", stato: "Aperta", responsabile: "", pm: "" },
  { codiceCommessa: "U260000D", anno: "2026", tipologia: "U", titolo: "GESTIONE AUTO AZIENDALI", cliente: "INGEGNO P & C S.R.L.", stato: "Aperta", responsabile: "", pm: "" },
];
